name: netshots
description: "A new Flutter project."
publish_to: 'none'

environment:
  sdk: ^3.8.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`.
dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^1.2.1
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  flutter_svg: ^2.2.0
  image_picker: ^1.0.4
  path_provider: ^2.1.2
  path: ^1.9.0
  firebase_core: ^4.3.0
  firebase_auth: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter:
  uses-material-design: true
  assets: 
    - assets/logo.png
    - assets/default_image_profile.jpg

flutter_launcher_icons:
  image_path: "assets/logo.png"
  android: "launcher_icon"
  min_sdk_android: 21
  ios: true
  remove_alpha_ios: true
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo_with_text.png
  android: true
  ios: true